//! OS clipboard backends. The only module allowed to contain platform-specific code.
//!
//! Reading and writing go through `arboard` on every platform. Each OS module (`Native`) adds what
//! arboard doesn't expose:
//!
//! - `is_private()`: whether the current content is marked "don't record this".
//! - `change_token()`: a cheap value that changes whenever the clipboard changes, so polling can
//!   skip full reads (and image decoding) when nothing happened. `None` means "can't tell
//!   cheaply; do a full read".

mod arboard;

#[cfg(all(
    unix,
    not(any(target_os = "macos", target_os = "android", target_os = "emscripten"))
))]
#[path = "linux.rs"]
mod os;
#[cfg(target_os = "macos")]
#[path = "macos.rs"]
mod os;
#[cfg(windows)]
#[path = "windows.rs"]
mod os;

pub(crate) use self::arboard::Backend;
pub(crate) use self::os::Native;

/// Format names that mark clipboard content as secret or not to be recorded.
///
/// - `org.nspasteboard.*`: macOS convention, see <http://nspasteboard.org>.
/// - `x-kde-passwordManagerHint`: Linux (KDE convention, also set by KeePassXC and others).
///
/// Windows uses registered formats with values instead of names alone; see `windows.rs`.
#[cfg_attr(windows, allow(dead_code))]
const PRIVATE_FORMAT_NAMES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
    "x-kde-passwordManagerHint",
];

/// Whether any of the clipboard's advertised format names marks the content as private.
#[cfg_attr(windows, allow(dead_code))]
pub(crate) fn has_private_marker<S: AsRef<str>>(formats: impl IntoIterator<Item = S>) -> bool {
    formats
        .into_iter()
        .any(|format| PRIVATE_FORMAT_NAMES.contains(&format.as_ref()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_password_manager_markers() {
        assert!(has_private_marker([
            "text/plain",
            "x-kde-passwordManagerHint"
        ]));
        assert!(has_private_marker([
            "public.utf8-plain-text",
            "org.nspasteboard.ConcealedType"
        ]));
        assert!(has_private_marker(["org.nspasteboard.TransientType"]));
    }

    #[test]
    fn ordinary_formats_are_not_private() {
        assert!(!has_private_marker([
            "text/plain;charset=utf-8",
            "text/html",
            "image/png"
        ]));
        assert!(!has_private_marker(Vec::<String>::new()));
    }

    #[test]
    fn marker_match_is_exact() {
        assert!(!has_private_marker(["x-kde-passwordManagerHint-extra"]));
        assert!(!has_private_marker(["X-KDE-PASSWORDMANAGERHINT"]));
    }
}
